name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Install AI dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          cd ai
          pip install -r requirements.txt

      - name: Compile contracts
        run: |
          cd contracts
          npm install
          npx hardhat compile

      - name: Placeholder tests
        run: echo "Add your unit tests here"
